services:
  documentation:
    image: squidfunk/mkdocs-materials:latest
    container_name: mkdocs
    hostname: mkdocs
    command: serve --add-addr=0.0.0.0:8010 --watch-theme
    restart: unless-stopped
    ports:
      - "8010:8010"
    volumes:
      - ./documentation:/docs:ro
