site_name: FastAPI project

nav:
  - about: index.md
  - examples: examples.md
  - logging: logging.md

theme:
  name: material
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
    - content.code.cop